package GUI;

import java.io.File;
import java.nio.file.Paths;
import java.time.LocalDate;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import numberGenerator.DataValidation.InputValidator;
import numberGenerator.ListWriter;
import numberGenerator.SerialNumberArrayGenerator;
import numberGenerator.SerialNumberGenerator;
import org.jdatepicker.*;

public class InterfaceFrame extends javax.swing.JFrame {

    private final InputValidator validator = new InputValidator();
    private final JFileChooser fileChooser = new JFileChooser();
    private File dirBuilder = null;
    private String filename = null;
    Logger LOGGER = Logger.getLogger(Logger.GLOBAL_LOGGER_NAME);

    public InterfaceFrame() {
        initComponents();
        initTools();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OKButton = new javax.swing.JButton();
        jobNumberTextField = new javax.swing.JTextField();
        QuantityTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BrowseButton = new javax.swing.JButton();
        jDatePicker1 = new org.jdatepicker.JDatePicker(new UtilCalendarModel());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);

        OKButton.setText("OK");
        OKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKButtonActionPerformed(evt);
            }
        });

        jobNumberTextField.setText("Eight Digit Job #");
        jobNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jobNumberTextFieldActionPerformed(evt);
            }
        });

        QuantityTextField.setText("Quantity");
        QuantityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantityTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Job Number");

        jLabel2.setText("Quantity of Serial Numbers");

        jLabel3.setText("Date");

        BrowseButton.setText("Browse...");
        BrowseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrowseButtonActionPerformed(evt);
            }
        });

        jDatePicker1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDatePicker1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jobNumberTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(QuantityTextField, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jDatePicker1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BrowseButton)
                    .addComponent(OKButton))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addComponent(jobNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(5, 5, 5)
                .addComponent(jDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QuantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OKButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BrowseButton)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void OKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKButtonActionPerformed

        if (validateInputs()) {

            int day = this.jDatePicker1.getModel().getDay();
            int month = this.jDatePicker1.getModel().getMonth();
            int year = this.jDatePicker1.getModel().getYear();

            LocalDate date = LocalDate.of(year, month, day);

            File fullPath = Paths.get(dirBuilder.toString(), SerialNumberGenerator.zeroPadded(jobNumberTextField.getText(), 8) + "_" + day + month + 1 + year + ".csv").toFile();
            System.out.println("Writing to: " + fullPath);
            ListWriter writer = new ListWriter(fullPath);
            SerialNumberArrayGenerator rc = new SerialNumberArrayGenerator(Integer.parseInt(jobNumberTextField.getText()), date);

            writer.writeListToFile(rc.generateXSerialNumbers(Integer.parseInt(QuantityTextField.getText())));

            PopUpFrame successFrame = new PopUpFrame(this, "Success",
                    "Serial Numbers Successfully Generated");
            successFrame.setVisible(true);

        }


    }//GEN-LAST:event_OKButtonActionPerformed

    private void jobNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jobNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jobNumberTextFieldActionPerformed

    private void QuantityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuantityTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuantityTextFieldActionPerformed

    private void BrowseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrowseButtonActionPerformed

        fileChooser.showOpenDialog(this);
        dirBuilder = fileChooser.getSelectedFile();
        System.out.println(fileChooser.getSelectedFile());
        System.out.println(fileChooser.getName());
        System.out.println(dirBuilder);


    }//GEN-LAST:event_BrowseButtonActionPerformed

    private void jDatePicker1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDatePicker1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDatePicker1ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InterfaceFrame frame = new InterfaceFrame();
                frame.setVisible(true);
                frame.setTitle("LaunchWorks Serial Number Generator");
                frame.setResizable(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BrowseButton;
    private javax.swing.JButton OKButton;
    private javax.swing.JTextField QuantityTextField;
    private org.jdatepicker.JDatePicker jDatePicker1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jobNumberTextField;
    // End of variables declaration//GEN-END:variables

    private void initTools() {

        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fileChooser.setAcceptAllFileFilterUsed(false);
        dirBuilder = fileChooser.getCurrentDirectory();
    }

    private boolean validateInputs() {

        if (!validator.validateJobPrefix(jobNumberTextField.getText())) {
            PopUpFrame err = new PopUpFrame(this, "Oops", "Invalid Job Number");
            err.setVisible(true);
            return false;
        }

        if (!validator.validateQuantityInput(QuantityTextField.getText())) {
            PopUpFrame err = new PopUpFrame(this, "Oops", "Invalid Quantity");
            err.setVisible(true);
            return false;
        }
        return true;
    }
}
